### ISSUE TITLE
Running on mac

### ISSUE THREAD

**Issue by diacoviello** [kwsch/EtumrepMMO#4]
I tried running the .exe on a Mac application known as "Wine" and received errors opening the program. I trusted z3 libraries and installed with python using `pip3 install z3-solver`. Error came back in console as:

`###BOTTLING### Enabling CoreAudio, Colors, Antialiasing  and flat menus...
/Applications/Wine.app/Contents/Frameworks/WBottler.framework/Resources/bottler.sh: line 134: /Applications/Wine.app/Contents/Resources/bin/wine: Bad CPU type in executable
### LOG ### Command '/Applications/Wine.app/Contents/Resources/bin/wine regedit /tmp/reg.reg' returned status 126.

###ERROR### Command '/Applications/Wine.app/Contents/Resources/bin/wine regedit /tmp/reg.reg' returned status 126.
Task returned with status 1.`

**Comment by kwsch** [comment]
https://docs.google.com/document/d/e/2PACX-1vRatJAj7yTNc06_KXls3aQm5xwxv9pcWdJPoco7gbiNctGzY7YBMyqdC0OgMS9FfBchHSGCzVaHJhT_/pub
